miiof_default:
    path: /
    defaults: { _controller: "Miiof\Controller\DefaultController::indexAction" }

miiof_create:
    path: /create
    defaults: { _controller: "Miiof\Controller\CreateController::indexAction" }

miiof_invoiceexample:
    path: /invoiceHTML
    defaults: { _controller: "Miiof\Controller\DefaultController::invoiceHtmlAction" }

miiof_generate:
    path: /generate
    defaults: { _controller: "Miiof\Controller\CreateController::generateAction" }
    methods:  [POST]
