miiof_default:
    path: /
    defaults: { _controller: "Miiof\Controller\DefaultController::indexAction" }

miiof_create:
    path: /create
    defaults: { _controller: "Miiof\Controller\CreateController::indexAction" }

miiof_generate:
    path: /generate
    defaults: { _controller: "Miiof\Controller\CreateController::generateAction" }
    methods:  [POST]

miiof_generateGET:
    path: /generate
    defaults: { _controller: "Miiof\Controller\CreateController::indexAction" }
    methods:  [GET]

miiof_save:
    path: /save/{invoiceKey}
    defaults: { _controller: "Miiof\Controller\SaveController::indexAction" }
    methods:  [GET]

miiof_invoice:
    path: /invoice/{invoiceKey}
    defaults: { _controller: "Miiof\Controller\DefaultController::invoiceAction" }
