miiof_default:
    path: /
    defaults: { _controller: "Miiof\Controller\DefaultController::indexAction" }

miiof_create:
    path: /create
    defaults: { _controller: "Miiof\Controller\CreateController::indexAction" }

miiof_generate:
    path: /generate
    defaults: { _controller: "Miiof\Controller\CreateController::generateAction" }
    methods:  [POST]

miiof_generateGET:
    path: /generate
    defaults: { _controller: "Miiof\Controller\CreateController::indexAction" }
    methods:  [GET]

miiof_save:
    path: /save/{invoiceKey}
    defaults: { _controller: "Miiof\Controller\SaveController::indexAction" }
    methods:  [GET]

miiof_invoice:
    path: /invoice/{invoiceKey}/{download}
    defaults: { _controller: "Miiof\Controller\DefaultController::invoiceAction", download: "view"}

miiof_dropbox_start:
    path: /dropbox/start
    defaults: { _controller: "Miiof\Controller\DropboxController::startAction" }

miiof_dropbox_finish:
    path: /dropbox/finish
    defaults: { _controller: "Miiof\Controller\DropboxController::finishAction" }

miiof_list_invoices:
    path: /listinvoices
    defaults: { _controller: "Miiof\Controller\CreateController::listInvoicesAction" }
